Traceback (most recent call last):
  File "main.py", line 11, in <module>
    from Model.mlp import MLPseq
  File "/home/hyuns6100/Mental-Heatlh-Care/Model/mlp.py", line 3, in <module>
    from .base import BASE
  File "/home/hyuns6100/Mental-Heatlh-Care/Model/base.py", line 4, in <module>
    from sklearn.metrics import matthews_corrcoef, f1_score
  File "/home/hyuns6100/anaconda3/envs/MentalHealth/lib/python3.8/site-packages/sklearn/__init__.py", line 83, in <module>
    from .base import clone
  File "/home/hyuns6100/anaconda3/envs/MentalHealth/lib/python3.8/site-packages/sklearn/base.py", line 19, in <module>
    from .utils import _IS_32BIT
  File "/home/hyuns6100/anaconda3/envs/MentalHealth/lib/python3.8/site-packages/sklearn/utils/__init__.py", line 22, in <module>
    from ._param_validation import Interval, validate_params
  File "/home/hyuns6100/anaconda3/envs/MentalHealth/lib/python3.8/site-packages/sklearn/utils/_param_validation.py", line 15, in <module>
    from .validation import _is_arraylike_not_scalar
  File "/home/hyuns6100/anaconda3/envs/MentalHealth/lib/python3.8/site-packages/sklearn/utils/validation.py", line 28, in <module>
    from ..utils._array_api import _asarray_with_order, _is_numpy_namespace, get_namespace
  File "/home/hyuns6100/anaconda3/envs/MentalHealth/lib/python3.8/site-packages/sklearn/utils/_array_api.py", line 9, in <module>
    from .fixes import parse_version
  File "/home/hyuns6100/anaconda3/envs/MentalHealth/lib/python3.8/site-packages/sklearn/utils/fixes.py", line 18, in <module>
    import scipy.stats
  File "/home/hyuns6100/anaconda3/envs/MentalHealth/lib/python3.8/site-packages/scipy/stats/__init__.py", line 485, in <module>
    from ._stats_py import *
  File "/home/hyuns6100/anaconda3/envs/MentalHealth/lib/python3.8/site-packages/scipy/stats/_stats_py.py", line 39, in <module>
    from scipy.spatial.distance import cdist
  File "/home/hyuns6100/anaconda3/envs/MentalHealth/lib/python3.8/site-packages/scipy/spatial/__init__.py", line 105, in <module>
    from ._kdtree import *
  File "/home/hyuns6100/anaconda3/envs/MentalHealth/lib/python3.8/site-packages/scipy/spatial/_kdtree.py", line 4, in <module>
    from ._ckdtree import cKDTree, cKDTreeNode
ImportError: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /home/hyuns6100/anaconda3/envs/MentalHealth/lib/python3.8/site-packages/scipy/spatial/_ckdtree.cpython-38-x86_64-linux-gnu.so)
